### ISSUE TITLE
@pello's update url

### ISSUE THREAD

**Issue by pello** [cryptax/confsec#19]
Hi Axelle,

There is a 1 missing  in @pello's list URL: https://twitter.com/pello/lists/conferences1/members

Regards,
Francois

**Comment by cryptax** [comment]
Bon j'ai fait une petite mise à jour... s'il y a qqch en particulier qui
manque, tu peux faire un pull request si tu preferes.
@+
Axelle

**Comment by fropert** [comment]
Merci Axelle,
Let's go pour un pull request la prochaine fois 👍 

François
