### ISSUE TITLE
Hackvens

### ISSUE THREAD

**Issue by seb280** [cryptax/confsec#62]
Hello,
I would like to add our infosec conference Hackvens to your referencing : https://hackvens.fr/
This event will take place on November, 22th 2024 in Lille. The ticket price is only 5€.

Hackvens is an annual one-day conference followed by a CTF night :
- A 100% Advens’ event (french cybersecurity company), no external sponsorship
- Nearly 200 cybersecurity and hacking enthusiasts gathered for the event, held each year in a different French city
- A dozen conferences on a variety of technical security topics (Redteam, R&D, AI, SOC, CSIRT, OT, IOT, Cloud, Linux, AD, etc.)
 - In-depth enriching challenges designed by our teams, putting participants to the test during a CTF.

I remain available for any further information you may need.
Thanks.

**Comment by cryptax** [comment]
that's very cool, we're mainly interested in the CFP date in this table. #c9522b668ffc080dd9ba84d3e90717aee0a4e0b3
